---
postsPerPage: 2
feedConfig:
    feedTitle: Rob's Blog
    feedDescription: bleh
    feedAuthorName: Rob Whitaker
    feedAuthorEmail: robjameswhitaker@gmail.com
    feedRoot: http://robwhitaker.com
...